# Generated by Django 3.2.9 on 2021-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Not well'), (3, 'Norm'), (4, 'Good'), (5, 'Amazing')], null=True),
        ),
    ]
